[package]
name = "mines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.9.0"

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["image"]
